import type { Metadata } from 'next';
import './globals.css';
import Logo from '@/components/Logo';

export const metadata: Metadata = {
  title: 'Todo List App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col w-full h-screen m-0 font-sans">
          <header className="flex justify-center items-center h-52 bg-[#0D0D0D]">
            <Logo />
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
